#!/bin/bash
shopt -s expand_aliases
Font_Black="\033[30m"
Font_Red="\033[31m"
Font_Green="\033[32m"
Font_Yellow="\033[33m"
Font_Blue="\033[34m"
Font_Purple="\033[35m"
Font_SkyBlue="\033[36m"
Font_White="\033[37m"
Font_Suffix="\033[0m"

echo -e "${Font_Red}【AD No.1】${Font_Suffix}"
echo -e "================================================"
echo -e "${Font_Yellow}香港、新加坡、美国Epyc SSD BGP 服务器！${Font_Suffix}"
echo -e "${Font_SkyBlue}✅ 香港129元/月、新加坡89元/月、硅谷59元/月${Font_Suffix}"
echo -e "${Font_SkyBlue}✅ 迪拜本地IP VPS Tiktok等电商业务首选${Font_Suffix}"
echo -e "${Font_Red}更多套餐优惠请访问 https://iPraft.com  或TG联系 @ipraft${Font_Suffix}"
echo -e "================================================"
